// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";

import AlertController from "./alert_controller";
application.register("alert", AlertController);

import ChatController from "./chat_controller";
application.register("chat", ChatController);

import ModalController from "./modal_controller";
application.register("modal", ModalController);

import ToggleFormController from "./toggle_form_controller";
application.register("toggle-form", ToggleFormController);

import TreeController from "./tree_controller";
application.register("tree", TreeController);

import UploadImageController from "./upload_image_controller";
application.register("upload-image", UploadImageController);

import VisibilityController from "./visibility_controller";
application.register("visibility", VisibilityController);
